language: minimal
addons:
  apt:
    packages:
    - jq

before_install:
- openssl aes-256-cbc -K $encrypted_64a105319298_key -iv $encrypted_64a105319298_iv
  -in ./contrib/travis/travis_deploy_key.enc -out ./contrib/travis/travis_deploy_key -d
- ssh-add ./contrib/travis/travis_deploy_key

script: "./contrib/travis/cron.sh"
