language: minimal
addons:
  apt:
    packages:
    - jq

before_install:
- openssl aes-256-cbc -K $encrypted_c03f6e2f5b7a_key -iv $encrypted_c03f6e2f5b7a_iv
  -in ./contrib/travis/travis_deploy_key.enc -out ./contrib/travis/travis_deploy_key -d
- chmod 0600 ./contrib/travis/travis_deploy_key
- eval "$(ssh-agent)"
- ssh-add ./contrib/travis/travis_deploy_key

script: "./contrib/travis/cron.sh"
